services:
  mysql:
    image: mysql:8.4.4
    container_name: mysql-local
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql_local
    volumes:
      - ./data:/var/lib/mysql